### ISSUE TITLE
Downloaded files naming convention

### ISSUE THREAD

**Issue by dockdude** [adrian-dobre/BlinkWebUI#16]
Hi,

Been using Blink Web UI and have downloaded bunch of files and the default filenames are somewhat cryptic.
Below is one example: 
948987989.mp4

Can you share how to translate the filename into a timestamp of the video clip?

Thank you for your work.

Steve

**Comment by adrian-dobre** [comment]
Hi @dockdude,
That name does not have anything to do with the timestamp, unfortunately. It's just the media file ID from blink. I'll try to have a look at this though, when I find some time, to include the timestamp in the downloaded file.

**Comment by adrian-dobre** [comment]
This has been fixed: https://github.com/adrian-dobre/BlinkWebUI/commit/b66ea01976f5de07cc46bb67222c495e1b6b66ba

**Comment by dockdude** [comment]
Perfect! Thanks Adrian. Would be nice now to eliminate the media file ID if it has no meaning.
Until Blink comes out with their Web Portal, if ever, I find your contribution very helpful.

Beer is on me.

**Comment by adrian-dobre** [comment]
Thank you! 🍻
Regarding file id, yeah, I suppose it doesn't bring any useful info to the user. I'll reopen the issue and remove it next time I touch the code.

**Comment by adrian-dobre** [comment]
Removed the file id from the downloaded file name.
