### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by BigBen2003** [adrian-dobre/BlinkWebUI#9]
== Englisch ==
Hi there,

Nodejs and then npm were installed on a freshly installed Debian 11 system.

The "npm install" command still ran without errors. Many warnings were displayed.

Only the "npm run build" command returned many errors.

The following commands were executed:

$ apt update && apt upgrade -y
$ apt install sudo curl nodejs -y

Installed the NPM command according to this webpage: https://stackoverflow.com/questions/48943416/bash-npm-command-not-found-in-debian-9-3
$ curl -L https://npmjs.org/install.sh | sudo sch

Command git installed:
$ apt install git -y

$ git clone https://github.com/adrian-dobre/BlinkWebUI.git
$ cd BlinkWebGUI
Installation created:
$ npm install
[install.log](https://github.com/adrian-dobre/BlinkWebUI/files/7915555/install.log)

Executed installation created:
$ npm run build
[build.log](https://github.com/adrian-dobre/BlinkWebUI/files/7915551/build.log)

As you can see, the last command WILL NOT be executed.

== Germany ==
Hallo,

auf einem frisch installiertem Debian 11 System wurde Nodejs und anschließend npm installiert.

Der Befehl "npm install" lief noch fehlerfrei durch. Es wurden viele Warnungen angezeigt.

Erst der Befehl "npm run build" lieferte viele Fehler.

Folgende Befehle wurde ausgeführt:

$ apt update && apt upgrade -y
$ apt install sudo curl nodejs -y

Gemäß dieser Webseite den NPM-Befehl  installiert: https://stackoverflow.com/questions/48943416/bash-npm-command-not-found-in-debian-9-3
$ curl -L https://npmjs.org/install.sh | sudo sh

Befehl git installiert:
$ apt install git -y

$ git clone https://github.com/adrian-dobre/BlinkWebUI.git
$ cd BlinkWebGUI
Installation erstellt:
$ npm install
[install.log](https://github.com/adrian-dobre/BlinkWebUI/files/7915555/install.log)

Erstellte Installationausgeführt:
$ npm run build
[build.log](https://github.com/adrian-dobre/BlinkWebUI/files/7915551/build.log)

Wie man sehen kann, wird der letzte Befehl nicht ausgeführt.

**Comment by adrian-dobre** [comment]
Thanks for reporting it.
Sorry for that, it seems some dependencies were updated and they were no longer compatible with initial versions. I locked the versions into place to (hopefully) prevent this from happening in the future. Also tried to fix all build warnings.
